Stack sprite
nthiery/laby-jupyter pull request #21
Opened 2020-07-19 12:34 UTC by Disatiler

Bonjour Monsieur,

Voici enfin le pull request de l'affichage des empilements de sprites.
Les modifications ont été faites dans les fichiers laby.hpp et solver.hpp ( qui devrait être ajouté au pull request des affichages de trace de pas) et dans laby-test.cpp pour tester les nouvelles méthodes créées.

Si vous avez des questions, n'hésitez pas à laisser un commentaire sur le pull request.

2020-07-20 11:00 UTC, nthiery requested changes
Merci Matthieu pour la PR. Le code est maintenant fonctionnel, il ne reste plus
qu'un peu de ménage à faire pour que la PR contienne les changements requis et rien
d'autre. Voir les commentaires.

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
> +    u8"→", u8"↑", u8"↓", u8"←", "x", "ŕ", "ẃ", "r", ".", "o", "w", " ", "R", "W","N","S","E","W"
Ces changements concernent l'autre PR. Merci de les enlever de celle-ci!

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>              carry = Tile::Void;
Ces changements concernent l'autre PR.

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
> +
idem

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>          history.push_back(value);
Merci pour le correctif! Il n'est pas lié à la PR actuelle. Merci de faire une PR séparée.

2020-07-20 11:00 UTC, nthiery commented on include/laby/widget.hpp
Merci de supprimer ce changement non requis.

2020-07-20 11:00 UTC, nthiery commented on laby-test.cpp
> +*/
Si ce test n'est finalement pas pertinent, le supprimer complètement.

2020-07-20 11:00 UTC, nthiery commented on laby-test.cpp
> +    */
Pourquoi en commentaire?

2020-07-20 11:00 UTC, nthiery commented on notebooks/this-is-crazy.ipynb
>    },
Annuler ces changements en revenant à la version originelle du notebook.

2020-07-20 11:00 UTC, nthiery commented on share/laby/levels/stack.laby
> +map:
Ce fichier est il encore nécessaire maintenant que les tests se font sur des mini-labyrinthes?
S'il ne l'est pas, le supprimer.

2020-07-20 11:00 UTC, nthiery commented on solve.hpp
> +#include "include/laby/global_fr.hpp"
Avoir un solveur est une jolie fonctionnalité. Mais qui n'est pas liée à l'empilement de sprite. À soumettre comme une PR séparée.

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
> +                s.insert(index, " class='tile' ");
À déplacer dans svg_image.

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>      return "<img src='"+filename(tile)+"' width=32 height=32>";
Ajouter le style 'tile', pour que, quelle que soit la valeur de use_inline_svg, le sprite soit dans la classe css 'tile'

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>      //////////////////////////////////////////////////////////////////////////
Inutile pour cette PR, n'est-ce pas?

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
Inutile pour cette PR, n'est-ce pas?

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
> +            //board.set(position, Tile::Carry)
À supprimer.

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>      bool sow() {
Dans l'autre PRI, il faudra réécrire sow() pour simplement appeler sow(SmallRocks).

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>      std::vector<Labyrinth> history;
Est-ce utile pour cette PR?

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>          play_direction(PlayDirection::Forward),
Idem

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
> +
Est-ce utile pour cette PR? Sinon supprimer.

2020-07-20 11:00 UTC, nthiery commented on include/laby/laby.hpp
>      return "<img src='"+filename(tile)+"' width=32 height=32>";
Au passage: vérifier dans les tests de svg_image que le style 'tile' apparaît bien, que inline_image soit à true ou false.
Pour inline_image=true, peut-être faire le test sur les premiers caractères du résultat.

2020-07-22 08:25 UTC, Disatiler reviewed
Voici les modifications que j'ai faite.
Je vais terminer les autres d'ici peu de temps.

2020-07-22 08:25 UTC, Disatiler commented on include/laby/laby.hpp
>      //////////////////////////////////////////////////////////////////////////
Oui

2020-07-22 08:25 UTC, Disatiler commented on share/laby/levels/stack.laby
> +map:
Non je vais le supprimer

2020-07-22 08:25 UTC, Disatiler commented on solve.hpp
> +#include "include/laby/global_fr.hpp"
Pas de problème, je vais le faire

2020-07-22 08:31 UTC, Disatiler commented on include/laby/laby.hpp
>      return "<img src='"+filename(tile)+"' width=32 height=32>";
Le soucis de donner le style 'tile' a tout les sprites fait que notre Labyrinthe se supperpose sur une seule cellule de l'output du notebook.

2020-08-17 10:48 UTC, nthiery commented
Ok, let's merge this PR as is. Modifying the svg on the fly is a hack, but it works, and this can be
improved in  a subsequent PR once a proper way to do it via css styling for svg images within
a div is found.

2020-08-17 10:48 UTC, nthiery approved these changes

2020-08-17 10:49 UTC, merged